/**
 * POST /api/export/upload
 *
 * Receives an exported video, uploads it to Google Drive, updates the
 * Airtable Content record with the drive link, and marks the project as done.
 *
 * Request: multipart/form-data with fields:
 *   - file: the video file (MP4)
 *   - projectId: the OpenCut project ID
 *   - filename: desired filename (auto-generated by client)
 *
 * Response: { driveFileId, driveViewLink }
 */

import { NextResponse, type NextRequest } from "next/server";
import { db, projects } from "@/lib/db";
import { eq } from "drizzle-orm";
import { getRequiredSession } from "@/lib/auth/session";
import { webEnv } from "@opencut/env/web";
import { updateContentRecord } from "@/lib/airtable/client";

// --- Google Drive upload via REST API ---

async function getServiceAccountToken(): Promise<string> {
	const keyPath = webEnv.GOOGLE_APPLICATION_CREDENTIALS;
	if (!keyPath) throw new Error("GOOGLE_APPLICATION_CREDENTIALS not set");

	const fs = await import("node:fs");
	const crypto = await import("node:crypto");
	const keyFile = JSON.parse(fs.readFileSync(keyPath, "utf-8"));

	const now = Math.floor(Date.now() / 1000);
	const header = Buffer.from(
		JSON.stringify({ alg: "RS256", typ: "JWT" }),
	).toString("base64url");
	const payload = Buffer.from(
		JSON.stringify({
			iss: keyFile.client_email,
			scope: "https://www.googleapis.com/auth/drive.file",
			aud: "https://oauth2.googleapis.com/token",
			iat: now,
			exp: now + 3600,
		}),
	).toString("base64url");

	const signature = crypto
		.sign("sha256", Buffer.from(`${header}.${payload}`), keyFile.private_key)
		.toString("base64url");

	const jwt = `${header}.${payload}.${signature}`;

	const tokenResponse = await fetch("https://oauth2.googleapis.com/token", {
		method: "POST",
		headers: { "Content-Type": "application/x-www-form-urlencoded" },
		body: `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${jwt}`,
	});

	if (!tokenResponse.ok) {
		throw new Error(`Token exchange failed: ${await tokenResponse.text()}`);
	}

	const { access_token } = (await tokenResponse.json()) as {
		access_token: string;
	};
	return access_token;
}

async function uploadToGoogleDrive({
	buffer,
	filename,
	mimeType,
	folderId,
}: {
	buffer: Buffer;
	filename: string;
	mimeType: string;
	folderId: string;
}): Promise<{ fileId: string; viewLink: string }> {
	const token = await getServiceAccountToken();

	// Use multipart upload (metadata + media in one request)
	const metadata = JSON.stringify({
		name: filename,
		parents: [folderId],
	});

	const boundary = "export_upload_boundary";
	const body = Buffer.concat([
		Buffer.from(
			`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: ${mimeType}\r\n\r\n`,
		),
		buffer,
		Buffer.from(`\r\n--${boundary}--`),
	]);

	const response = await fetch(
		"https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink",
		{
			method: "POST",
			headers: {
				Authorization: `Bearer ${token}`,
				"Content-Type": `multipart/related; boundary=${boundary}`,
			},
			body,
		},
	);

	if (!response.ok) {
		const errorBody = await response.text();
		throw new Error(
			`Google Drive upload failed (${response.status}): ${errorBody}`,
		);
	}

	const result = (await response.json()) as {
		id: string;
		webViewLink: string;
	};

	return { fileId: result.id, viewLink: result.webViewLink };
}

// --- Handler ---

export async function POST(request: NextRequest) {
	const session = await getRequiredSession();
	if (!session) {
		return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
	}

	const folderId = webEnv.GOOGLE_DRIVE_EXPORT_FOLDER_ID;
	if (!folderId || folderId === "placeholder") {
		return NextResponse.json(
			{ error: "GOOGLE_DRIVE_EXPORT_FOLDER_ID not configured" },
			{ status: 500 },
		);
	}

	// Parse multipart form data
	const formData = await request.formData();
	const file = formData.get("file") as File | null;
	const projectId = formData.get("projectId") as string | null;
	const filename = formData.get("filename") as string | null;

	if (!file || !projectId || !filename) {
		return NextResponse.json(
			{ error: "Missing required fields: file, projectId, filename" },
			{ status: 400 },
		);
	}

	// Verify project exists and user has access
	const [project] = await db
		.select({
			id: projects.id,
			name: projects.name,
			assignedUserId: projects.assignedUserId,
		})
		.from(projects)
		.where(eq(projects.id, projectId))
		.limit(1);

	if (!project) {
		return NextResponse.json({ error: "Project not found" }, { status: 404 });
	}

	const isAdmin = session.user.role === "admin";
	if (!isAdmin && project.assignedUserId !== session.user.id) {
		return NextResponse.json({ error: "Forbidden" }, { status: 403 });
	}

	try {
		// Upload to Google Drive
		const arrayBuffer = await file.arrayBuffer();
		const buffer = Buffer.from(arrayBuffer);

		const { fileId, viewLink } = await uploadToGoogleDrive({
			buffer,
			filename,
			mimeType: file.type || "video/mp4",
			folderId,
		});

		// Mark project as done
		await db
			.update(projects)
			.set({ status: "done", updatedAt: new Date() })
			.where(eq(projects.id, projectId));

		// Try to update Airtable Content record (best-effort)
		// The project name contains the contentId: format_date_contentId
		const contentIdMatch = project.name.match(/_(\w+)$/);
		const contentId = contentIdMatch?.[1];

		if (
			contentId &&
			webEnv.AIRTABLE_API_KEY &&
			webEnv.AIRTABLE_API_KEY !== "placeholder"
		) {
			try {
				await updateContentRecord({
					recordId: contentId,
					fields: {
						"Final Video": viewLink,
					},
				});
			} catch (err) {
				// Non-fatal — log and continue
				console.error("Failed to update Airtable after export:", err);
			}
		}

		return NextResponse.json({
			driveFileId: fileId,
			driveViewLink: viewLink,
			projectStatus: "done",
		});
	} catch (err) {
		console.error("Export upload failed:", err);
		return NextResponse.json(
			{
				error: "Upload failed",
				message: err instanceof Error ? err.message : String(err),
			},
			{ status: 500 },
		);
	}
}
